package de.autopolish.nativeapp;

import android.app.*;
import android.content.*;
import android.net.Uri;
import android.os.Bundle;
import android.provider.CalendarContract;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.math.BigDecimal;

/** Native editors and lists backed by the same contracts as the web application. */
public class BusinessActivity extends MediaFormActivity {
    private String module,id="",uploadId=UUID.randomUUID().toString(),secret="",link="";
    private JSONObject model=new JSONObject();
    private final LinkedHashMap<String,EditText> fields=new LinkedHashMap<>();
    private final LinkedHashMap<String,Spinner> choices=new LinkedHashMap<>();
    private final LinkedHashMap<String,String[]> choiceValues=new LinkedHashMap<>();
    private final LinkedHashMap<String,CheckBox> checks=new LinkedHashMap<>();
    private final ArrayList<Row> rows=new ArrayList<>();
    private LinearLayout rowsView;
    private TextView totals,status;
    private Button saveButton;
    private boolean busy,loaded;
    private JSONObject restored;
    interface Job { JSONObject run() throws Exception; }
    public static void open(android.content.Context c,String module,String id){Intent i=new Intent(c,BusinessActivity.class).putExtra("module",module);if(id!=null)i.putExtra("record_id",id);c.startActivity(i);}
    @Override protected void onCreate(Bundle state){super.onCreate(state);module=getIntent().getStringExtra("module");if(module==null)module="offer";id=getIntent().getStringExtra("record_id");if(id==null)id="";
        if(state!=null){try{restored=new JSONObject(state.getString("draft","{}"));}catch(Exception ignored){}uploadId=state.getString("uploadId",uploadId);link=state.getString("link","");}
        load();
    }
    @Override protected void onSaveInstanceState(Bundle out){if(loaded&&!fields.isEmpty()){try{JSONObject draft=captureDraft();draft.remove("systemPassword");draft.remove("discountPassword");out.putString("draft",draft.toString());}catch(Exception ignored){}}out.putString("uploadId",uploadId);out.putString("link",link);super.onSaveInstanceState(out);}
    private String heading(){switch(module){case "offer":return "Angebot erstellen";case "customer-link":return "Kundenauftrag senden";case "work-card":return "Arbeitskarte";case "work-cards":return "Arbeitskarten";case "tire":return "Radeinlagerung";case "tires":return "Radeinlagerung Formulare";case "notes":case "note":return "Notizen";case "letterhead":return "Briefpapier";case "order":return id.isEmpty()?"Neuer Fahrzeugauftrag":"Auftrag bearbeiten";case "search":return "Suche in allen Kategorien";case "calendar":return "Auto-Polish Kalender";default:return "Auto-Polish";}}
    private void reset(){saveButton=null;fields.clear();choices.clear();choiceValues.clear();checks.clear();rows.clear();rowsView=null;totals=null;pad=null;shell(heading());status=Ui.text(this,"",14,Ui.RED,false);content.addView(status);}
    private void load(){reset();
        if(module.equals("notes")||module.equals("note")){if(secret.isEmpty())secret=getIntent().getStringExtra("notes_password");if(secret==null||secret.isEmpty()){askNotesPassword();return;}}
        if(module.equals("work-cards")||module.equals("tires")||module.equals("notes")||module.equals("search")){list();return;}
        if(module.equals("calendar")){calendar();return;}
        if(restored!=null){model=restored;restored=null;render();return;}
        if(module.equals("letterhead")){job(()->ApiClient.request("GET","/api/letterhead",null),r->{model=r.getJSONObject("config");render();});return;}
        if(module.equals("note")){try{model=new JSONObject(getIntent().getStringExtra("record"));}catch(Exception ignored){model=new JSONObject();}render();return;}
        if(!id.isEmpty()){String api=module.equals("order")?"orders":module.equals("tire")?"tire-storages":"work-cards";job(()->ApiClient.request("GET","/api/"+api+"?id="+Uri.encode(id),null),r->{model=r.getJSONObject(module.equals("order")?"order":"record");loadMedia();render();});return;}
        model=json("id",uploadId,"date",java.time.LocalDate.now().toString(),"price","55,00","season","Winterreifen","wheelType","Kompletträder","status","eingelagert","storageNumber","","orderNumber","AK-"+stamp());if(module.equals("tire")){job(()->{for(int n=0;n<40;n++){String candidate=String.format(Locale.ROOT,"RAD-%04d",1+new java.security.SecureRandom().nextInt(9999));JSONArray found=ApiClient.request("GET","/api/tire-storages?q="+candidate,null).getJSONArray("records");boolean used=false;for(int j=0;j<found.length();j++)if(candidate.equals(found.getJSONObject(j).optString("storageNumber")))used=true;if(!used)return json("number",candidate);}throw new IllegalStateException("Keine freie Nummer gefunden. Bitte erneut versuchen.");},r->{model.put("storageNumber",r.getString("number"));render();});}else render();
    }
    private static String stamp(){return java.time.LocalDate.now().toString().replace("-","")+"-"+UUID.randomUUID().toString().substring(0,6).toUpperCase(Locale.ROOT);}
    private void loadMedia(){photos.clear();JSONArray a=BusinessData.array(model,module.equals("order")?"vehiclePhotoKeys":"photoKeys",module.equals("order")?"vehiclePhotoKeysJson":"photoKeysJson");for(int n=0;n<a.length();n++)photos.add(a.optString(n));registration=model.optString("vehicleRegistrationKey");signature=model.optString("signatureKey");}
    private void render(){loaded=true;reset();loaded=true;
        switch(module){
            case "offer":case "order":offerOrOrder();break;
            case "customer-link":note("Einmaligen Link erstellen. Der Kunde erfasst seine Angaben, Fotos und Unterschrift. Der Link ist sieben Tage gültig.");input("email","E-Mail-Adresse des Kunden");saveButton=action("Neuen Kundenlink erstellen",()->job(()->ApiClient.request("POST","/api/portal-links",json("kind","order")),this::showLink));if(!link.isEmpty())showLinkUnchecked();break;
            case "work-card":workCard();break;
            case "tire":tire();break;
            case "note":noteForm();break;
            case "letterhead":letterhead();break;
        }
    }
    private EditText input(String key,String label){EditText e=field(label,model.optString(key,""),key.toLowerCase(Locale.ROOT).contains("password"));fields.put(key,e);if(key.equals("email"))e.setInputType(33);else if(key.equals("phone"))e.setInputType(3);return e;}
    private EditText multiline(String key,String label){EditText e=input(key,label);e.setSingleLine(false);e.setInputType(131073);e.setGravity(Gravity.TOP);e.setMinLines(3);e.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(this,110)));return e;}
    private Spinner select(String key,String label,String[] values){return select(key,label,values,values);}
    private Spinner select(String key,String label,String[] values,String[] labels){note(label);Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));String current=model.optString(key,values[0]);for(int i=0;i<values.length;i++)if(values[i].equals(current))s.setSelection(i);content.addView(s,new LinearLayout.LayoutParams(-1,Ui.dp(this,52)));choices.put(key,s);choiceValues.put(key,values);return s;}
    private void check(String key,String label){CheckBox c=new CheckBox(this);c.setText(label);c.setTextColor(Ui.ink(this));c.setChecked(model.optBoolean(key));content.addView(c);checks.put(key,c);}
    private void customer(boolean address){title("Kunde und Fahrzeug");input("firstName","Vorname *");input("lastName","Nachname *");input("email","E-Mail");input("phone","Telefon");if(address){input("street","Straße und Hausnummer");input("postalCode","PLZ");input("city","Ort");}input("vehicle","Hersteller / Modell");input("licensePlate","Kennzeichen"+(!module.equals("offer")?" *":""));if(!module.equals("tire")){input("vin","FIN");if(module.equals("order"))input("mileage","Kilometerstand");}}
    private void offerOrOrder(){customer(module.equals("order"));if(module.equals("offer"))multiline("notes","Hinweise zum Angebot");title("Leistungen und Nettopreise");rowsView=Ui.vertical(this,0);content.addView(rowsView);JSONArray items=BusinessData.array(model,module.equals("offer")?"items":"services","servicesJson");for(int i=0;i<items.length();i++){JSONObject row=items.optJSONObject(i);if(row!=null)addRow(row,false);}if(rows.isEmpty())addRow(json("name","Fahrzeugaufbereitung","price",0),false);action("Leistung hinzufügen",()->addRow(new JSONObject(),false));
        if(module.equals("order")){EditText discount=input("discountPercent","Rabatt in Prozent (0–100)");if(value(discount).isEmpty())discount.setText("0");discount.setInputType(2);discount.addTextChangedListener(watch(this::updateTotal));input("discountPassword","System-Passwort für Rabatt");}
        totals=Ui.text(this,"",18,Ui.BLACK,true);Ui.marginTop(totals,this,16);content.addView(totals);updateTotal();media(true,module.equals("order"));saveButton=action(module.equals("offer")?"Angebotslink erstellen":"Auftrag speichern",this::save);
        if(!link.isEmpty())showLinkUnchecked();if(!id.isEmpty()&&module.equals("order"))documentActions("orders");
    }
    private static TextWatcher watch(Runnable r){return new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){r.run();}public void afterTextChanged(Editable e){}};}
    private void addRow(JSONObject item,boolean task){LinearLayout card=Ui.vertical(this,10);card.setBackground(Ui.bordered(android.graphics.Color.WHITE,Ui.BORDER,12,this));EditText name=Ui.input(this,task?"Arbeitsschritt":"Leistung");name.setText(item.optString(task?"text":"name"));card.addView(name);EditText price=Ui.input(this,"Nettopreis in €");CheckBox done=new CheckBox(this);done.setText("Erledigt");done.setTextColor(Ui.ink(this));done.setChecked(item.optBoolean("done"));if(task)card.addView(done);else{price.setInputType(8194);price.setText(item.has("rawPrice")?item.optString("rawPrice"):item.has("price")?String.format(Locale.GERMANY,"%.2f",item.optDouble("price")):"");card.addView(price);price.addTextChangedListener(watch(this::updateTotal));name.addTextChangedListener(watch(this::updateTotal));}Row row=new Row(item.optString("id",UUID.randomUUID().toString()),name,price,done,task);rows.add(row);Button remove=Ui.button(this,"Entfernen",Ui.RED);card.addView(remove);remove.setOnClickListener(v->{rows.remove(row);rowsView.removeView(card);updateTotal();});LinearLayout.LayoutParams params=new LinearLayout.LayoutParams(-1,-2);params.topMargin=Ui.dp(this,10);rowsView.addView(card,params);updateTotal();}
    private JSONArray items(boolean strict)throws Exception{JSONArray result=new JSONArray();for(Row row:rows){String name=value(row.name).trim();if(name.isEmpty()){if(strict&&!row.task&&!value(row.price).trim().isEmpty()&&BusinessData.money(value(row.price)).signum()>0)throw new IllegalArgumentException("Bitte eine Bezeichnung für jede berechnete Leistung eingeben.");continue;}result.put(row.task?json("id",row.id,"text",name,"done",row.done.isChecked()):json("id",row.id,"name",name,"price",BusinessData.money(value(row.price)).doubleValue()));}return result;}
    private int discount(){String value=fields.containsKey("discountPercent")?value(fields.get("discountPercent")).trim():"0";return value.isEmpty()?0:Integer.parseInt(value);}
    private void updateTotal(){if(totals==null)return;try{JSONObject t=BusinessData.totals(items(false),discount());totals.setText(String.format(Locale.GERMANY,"Netto: %.2f €\n19 %% MwSt.: %.2f €\nGesamt: %.2f €",t.getDouble("net"),t.getDouble("vat"),t.getDouble("gross")));}catch(Exception e){totals.setText("Bitte Preise und Rabatt prüfen.");}}
    private void workCard(){title("Auftrag und Mitarbeiter");input("orderNumber","Auftragsnummer *");input("customer","Kunde");input("vehicle","Fahrzeug");input("licensePlate","Kennzeichen");if(model.has("workDate")&&!model.has("date"))put("date",model.optString("workDate"));input("date","Datum (JJJJ-MM-TT)");input("employee","Mitarbeiter");multiline("notes","Hinweise");title("Arbeitsschritte");rowsView=Ui.vertical(this,0);content.addView(rowsView);JSONArray tasks=BusinessData.array(model,"tasks","tasksJson");for(int n=0;n<tasks.length();n++)addRow(tasks.optJSONObject(n),true);if(rows.isEmpty())addRow(new JSONObject(),true);action("Arbeitsschritt hinzufügen",()->addRow(new JSONObject(),true));media(false,false);saveButton=action("Arbeitskarte speichern",this::save);if(!id.isEmpty())documentActions("work-cards");}
    private void tire(){if(!id.isEmpty())action("Formular ansehen",()->PdfActivity.open(this,"/api/tire-storages/"+Uri.encode(id)+"/pdf","Radeinlagerung"));if(model.has("storageDate")&&!model.has("date"))put("date",model.optString("storageDate"));if(model.has("priceCents")&&!model.has("price"))put("price",String.format(Locale.GERMANY,"%.2f",model.optInt("priceCents")/100.0));input("storageNumber","Einlagerungsnummer *");input("date","Datum (JJJJ-MM-TT) *");select("status","Status",new String[]{"eingelagert","ausgelagert"});customer(true);select("season","Saison",new String[]{"Winterreifen","Sommerreifen","Ganzjahresreifen"});select("wheelType","Art",new String[]{"Kompletträder","Reifen ohne Felgen"});input("manufacturer","Reifenhersteller");input("dot","DOT");input("sizeFront","Reifengröße vorne");input("sizeRear","Reifengröße hinten");title("Zustand");input("treadFrontLeft","Profiltiefe vorne links (mm)");input("treadFrontRight","Profiltiefe vorne rechts (mm)");input("treadRearLeft","Profiltiefe hinten links (mm)");input("treadRearRight","Profiltiefe hinten rechts (mm)");check("damaged","Beschädigungen vorhanden");multiline("notes","Hinweise und Schäden");input("storageLocation","Lagerplatz *");EditText price=input("price","Saisonpreis in €");price.setInputType(8194);input("systemPassword","System-Passwort bei Preisänderung");note("Saisonpreis: 55,00 €. Preisänderungen prüft der Server mit dem System-Passwort.");media(false,true);saveButton=action("Radeinlagerung speichern",this::save);if(!id.isEmpty())documentActions("tire-storages");}
    private void noteForm(){input("title","Titel");multiline("content","Notiztext *");select("priority","Priorität",new String[]{"normal","wichtig","dringend","erledigt"});saveButton=action("Notiz speichern",this::save);if(!id.isEmpty())action("Notiz löschen",()->confirmDelete("notes"));}
    private void put(String k,Object v){try{model.put(k,v);}catch(Exception e){throw new IllegalArgumentException(e);}}
    private JSONObject collect(boolean strict)throws Exception{JSONObject result=new JSONObject(model.toString());for(Map.Entry<String,EditText> e:fields.entrySet())result.put(e.getKey(),value(e.getValue()).trim());for(String k:choices.keySet())result.put(k,choiceValues.get(k)[choices.get(k).getSelectedItemPosition()]);for(String k:checks.keySet())result.put(k,checks.get(k).isChecked());if(module.equals("offer")||module.equals("order")){JSONArray items=items(strict);result.put(module.equals("offer")?"items":"services",items);int discount=module.equals("order")?discount():0;result.put("discountPercent",discount);JSONObject t=BusinessData.totals(items,discount);for(String k:new String[]{"net","vat","gross"})result.put(k,t.get(k));if(strict&&items.length()==0)throw new IllegalArgumentException("Bitte mindestens eine Leistung eingeben.");}if(module.equals("work-card"))result.put("tasks",items(strict));return result;}
    private void required(JSONObject data,String... keys)throws Exception{for(String k:keys)if(data.optString(k).trim().isEmpty()){EditText field=fields.get(k);if(field!=null){field.setError("Pflichtfeld");field.requestFocus();}throw new IllegalArgumentException("Bitte alle Pflichtfelder ausfüllen.");}}
    private void save(){if(busy||!loaded)return;try{JSONObject data=collect(true);if(module.equals("offer")||module.equals("order")||module.equals("tire"))required(data,"firstName","lastName");if(module.equals("order")||module.equals("tire"))required(data,"licensePlate");if(module.equals("work-card"))required(data,"orderNumber");if(module.equals("tire")){required(data,"storageNumber","date","storageLocation");if(id.isEmpty()&&!data.optString("storageNumber").matches("RAD-[0-9]{1,4}"))throw new IllegalArgumentException("Einlagerungsnummer: RAD- und höchstens vier Ziffern.");BusinessData.money(data.getString("price"));if(signature.isEmpty()&&(pad==null||!pad.hasInk()))throw new IllegalArgumentException("Bitte unterschreiben.");}if(module.equals("note"))required(data,"content");if(data.has("date")&&(module.equals("tire")||module.equals("work-card")))java.time.LocalDate.parse(data.getString("date"));if(module.equals("letterhead"))validateLetterhead(data);
        MediaSnapshot media=snapshot();String recordId=id.isEmpty()?uploadId:id;String password=secret;String currentId=id;
        job(()->{switch(module){
            case "offer":media.apply(data,uploadId,"vehiclePhotoKeys",true);data.put("offerNumber","ANG-"+stamp());return ApiClient.request("POST","/api/portal-links",json("kind","offer","payload",data));
            case "order":media.apply(data,recordId,"vehiclePhotoKeys",true);data.put("id",recordId);return ApiClient.saveOrder(currentId,data);
            case "work-card":media.apply(data,recordId,"photoKeys",false);return ApiClient.request(currentId.isEmpty()?"POST":"PUT","/api/work-cards"+(currentId.isEmpty()?"":"?id="+Uri.encode(currentId)),data);
            case "tire":media.apply(data,recordId,"photoKeys",false);data.put("id",recordId);return ApiClient.request(currentId.isEmpty()?"POST":"PUT","/api/tire-storages",data);
            case "note":if(!currentId.isEmpty())data.put("id",currentId);return ApiClient.request(currentId.isEmpty()?"POST":"PUT","/api/notes",data,password);
            case "letterhead":if(!registration.isEmpty())data.put("logoKey",uploadRef(registration,uploadId,"logo"));return ApiClient.request("POST","/api/letterhead",data);
            default:throw new IllegalStateException("Unbekanntes Formular.");}
        },r->{if(module.equals("offer")){showLink(r);return;}if(module.equals("letterhead")){model=r.getJSONObject("config");status.setTextColor(Ui.readable(this,Ui.GREEN));status.setText("Briefpapier gespeichert.");return;}message("Gespeichert.");if(module.equals("order")){String order=r.getJSONObject("order").getString("id");startActivity(new Intent(this,OrderDetailActivity.class).putExtra("order_id",order));}finish();});
    }catch(Exception e){status.setText(e instanceof java.time.format.DateTimeParseException?"Bitte ein gültiges Datum als JJJJ-MM-TT eingeben.":e.getMessage());}}
    private void job(Job job,Result success){if(busy)return;busy=true;enable(content,false);status.setTextColor(Ui.muted(this));status.setText("Wird geladen / gespeichert …");if(saveButton!=null)saveButton.setEnabled(false);requests.execute(()->{try{JSONObject r=job.run();runOnUiThread(()->{if(isDestroyed())return;busy=false;enable(content,true);if(saveButton!=null)saveButton.setEnabled(true);status.setText("");try{success.accept(r);}catch(Exception e){status.setTextColor(Ui.RED);status.setText(e.getMessage());}});}catch(Exception e){runOnUiThread(()->{if(isDestroyed())return;busy=false;enable(content,true);if(saveButton!=null)saveButton.setEnabled(true);status.setTextColor(Ui.RED);status.setText(e.getMessage());if(module.equals("notes")||module.equals("note")){secret="";getIntent().removeExtra("notes_password");action("Passwort erneut eingeben",this::askNotesPassword);}else if(!loaded)action("Erneut versuchen",this::load);});}});}
    private void enable(View view,boolean enabled){view.setEnabled(enabled);if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++)enable(group.getChildAt(i),enabled);}}
    private JSONObject captureDraft()throws Exception{
        JSONObject result=new JSONObject(model.toString());for(String key:fields.keySet())result.put(key,value(fields.get(key)));for(String key:choices.keySet())result.put(key,choiceValues.get(key)[choices.get(key).getSelectedItemPosition()]);for(String key:checks.keySet())result.put(key,checks.get(key).isChecked());
        if(rowsView!=null){JSONArray data=new JSONArray();for(Row row:rows)data.put(row.task?json("id",row.id,"text",value(row.name),"done",row.done.isChecked()):json("id",row.id,"name",value(row.name),"rawPrice",value(row.price)));result.put(module.equals("work-card")?"tasks":module.equals("offer")?"items":"services",data);}return result;
    }
    private void showLink(JSONObject r)throws Exception{link=r.getString("link");showLinkUnchecked();}
    private void showLinkUnchecked(){title("Link ist bereit");TextView display=Ui.text(this,link,15,Ui.BLACK,false);display.setTextIsSelectable(true);content.addView(display);final String created=link;action("Link kopieren",()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Auto-Polish",created));message("Link kopiert.");});action("Link teilen",()->external(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,"Auto-Polish: "+created),"Link teilen")));action("Per E-Mail senden",()->{String email=fields.containsKey("email")?value(fields.get("email")).trim():"";if(!android.util.Patterns.EMAIL_ADDRESS.matcher(email).matches()){message("Bitte die E-Mail-Adresse des Kunden eingeben.");return;}external(new Intent(Intent.ACTION_SENDTO,Uri.parse("mailto:"+Uri.encode(email)+"?subject="+Uri.encode(module.equals("offer")?"Ihr Angebot von Auto-Polish":"Auto-Polish Fahrzeugauftrag")+"&body="+Uri.encode("Ihr persönlicher Link: "+created))));});action("Kundenansicht öffnen",()->external(new Intent(Intent.ACTION_VIEW,Uri.parse(created))));}
    private void external(Intent i){try{startActivity(i);}catch(ActivityNotFoundException e){message("Keine passende App installiert.");}}
    private void documentActions(String api){action("Dokument ansehen",()->PdfActivity.open(this,"/api/"+api+"/"+Uri.encode(id)+"/pdf",heading()));action("Löschen",()->confirmDelete(api));if(api.equals("orders"))action("Als Arbeitskarte speichern",()->job(()->ApiClient.request("POST","/api/work-cards",json("sourceOrderId",id)),r->{BusinessActivity.open(this,"work-card",r.getJSONObject("record").getString("id"));}));}
    private void confirmDelete(String api){EditText password=Ui.input(this,"System-Passwort");password.setInputType(129);AlertDialog.Builder b=new AlertDialog.Builder(this).setTitle("Datensatz löschen?").setMessage("Dieser Datensatz wird auf dem Server gelöscht.").setNegativeButton("Abbrechen",null);if(!api.equals("notes"))b.setView(password);b.setPositiveButton("Löschen",(d,n)->{String p=value(password);job(()->ApiClient.request("DELETE","/api/"+api+(api.equals("notes")?"":"?id="+Uri.encode(id)),json("id",id,"password",p),api.equals("notes")?secret:null),r->{message("Gelöscht.");finish();});}).show();}
    private void askNotesPassword(){EditText p=Ui.input(this,"System-Passwort");p.setInputType(129);new AlertDialog.Builder(this).setTitle("Notizen entsperren").setView(p).setCancelable(false).setNegativeButton("Abbrechen",(d,n)->finish()).setPositiveButton("Öffnen",(d,n)->{secret=value(p);job(()->ApiClient.request("GET","/api/notes",null,secret),r->{load();});}).show();}
    private void list(){loaded=true;EditText query=field("Suchen",getIntent().getStringExtra("query")==null?"":getIntent().getStringExtra("query"),false);LinearLayout results=Ui.vertical(this,0);Runnable refresh=()->{String q=value(query).trim();String api=module.equals("work-cards")?"work-cards":module.equals("tires")?"tire-storages":module.equals("notes")?"notes":"global-search";if(module.equals("search")&&q.length()<2){status.setText("Bitte mindestens zwei Zeichen eingeben.");return;}job(()->ApiClient.request("GET","/api/"+api+(api.equals("notes")||api.equals("work-cards")?"":"?q="+Uri.encode(q)),null,api.equals("notes")?secret:null),r->{results.removeAllViews();JSONArray a=r.getJSONArray(module.equals("notes")?"notes":module.equals("search")?"results":"records");int matches=0;for(int n=0;n<a.length();n++){JSONObject item=a.getJSONObject(n);if((module.equals("notes")||module.equals("work-cards"))&&!item.toString().toLowerCase(Locale.ROOT).contains(q.toLowerCase(Locale.ROOT)))continue;matches++;String label=module.equals("notes")?item.optString("title","Notiz")+" · "+item.optString("priority")+"\n"+item.optString("content"):module.equals("search")?item.optString("kind")+" · "+item.optString("number")+"\n"+item.optString("title")+" · "+item.optString("subtitle"):item.optString("storageNumber",item.optString("orderNumber"))+"\n"+item.optString("licensePlate")+" · "+item.optString("customer",(item.optString("firstName")+" "+item.optString("lastName")).trim());TextView row=Ui.text(this,label,16,Ui.BLACK,true);row.setPadding(Ui.dp(this,14),Ui.dp(this,18),Ui.dp(this,14),Ui.dp(this,18));row.setBackground(Ui.bordered(android.graphics.Color.WHITE,Ui.BORDER,12,this));row.setOnClickListener(v->{String target=module.equals("tires")?"tire":module.equals("notes")?"note":"work-card";if(module.equals("search"))target=item.optString("kind").equals("Auftrag")?"order":item.optString("kind").equals("Arbeitskarte")?"work-card":"tire";Intent intent=new Intent(this,BusinessActivity.class).putExtra("module",target).putExtra("record_id",item.optString("id"));if(target.equals("note"))intent.putExtra("record",item.toString()).putExtra("notes_password",secret);startActivity(intent);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=Ui.dp(this,10);results.addView(row,lp);}if(matches==0)results.addView(Ui.text(this,"Keine Einträge gefunden.",16,Ui.MUTED,false));});};int at=content.indexOfChild(query);content.removeView(query);content.addView(Ui.scanField(this,query,code->refresh.run()),at,new LinearLayout.LayoutParams(-1,Ui.dp(this,52)));action("Suchen / Aktualisieren",refresh);if(!module.equals("search"))action("Neu erstellen",()->{Intent i=new Intent(this,BusinessActivity.class).putExtra("module",module.equals("tires")?"tire":module.equals("notes")?"note":"work-card");if(module.equals("notes"))i.putExtra("notes_password",secret);startActivity(i);});content.addView(results);refresh.run();}
    @Override protected void onRestart(){super.onRestart();if(module.equals("work-cards")||module.equals("tires")||module.equals("notes"))load();}
    private void calendar(){loaded=true;CalendarView calendar=new CalendarView(this);content.addView(calendar);final long[] day={System.currentTimeMillis()};calendar.setOnDateChangeListener((v,y,m,d)->{java.util.Calendar c=java.util.Calendar.getInstance();c.set(y,m,d,9,0);day[0]=c.getTimeInMillis();});action("Tag in Kalender-App öffnen",()->external(new Intent(Intent.ACTION_VIEW,Uri.parse("content://com.android.calendar/time/"+day[0])).putExtra(CalendarContract.EXTRA_EVENT_BEGIN_TIME,day[0])));action("Termin anlegen",()->external(new Intent(Intent.ACTION_INSERT,CalendarContract.Events.CONTENT_URI).putExtra(CalendarContract.EXTRA_EVENT_BEGIN_TIME,day[0]).putExtra(CalendarContract.EXTRA_EVENT_END_TIME,day[0]+3600000).putExtra(CalendarContract.Events.TITLE,"Auto-Polish")));action("Kalender-Einstellungen",()->startActivity(new Intent(this,SettingsActivity.class)));note("Termine öffnest und speicherst du in deiner installierten Kalender-App. Dort den gewünschten Auto-Polish-Kalender auswählen.");}
    private static final class Row {final String id;final EditText name,price;final CheckBox done;final boolean task;Row(String id,EditText name,EditText price,CheckBox done,boolean task){this.id=id;this.name=name;this.price=price;this.done=done;this.task=task;}}

    private void letterhead(){title("Firma und Kontaktdaten");String[][] text={{"companyName","Firmenname"},{"subtitle","Untertitel"},{"street","Straße"},{"postalCity","PLZ und Ort"},{"phone","Telefon"},{"website","Website"},{"email","E-Mail"},{"bank","Bankverbindung"},{"taxNumber","Steuernummer"},{"owner","Inhaber"}};for(String[] f:text)input(f[0],f[1]);if(registration.isEmpty())registration=model.optString("logoKey","");action("Logo auswählen",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,403);});if(!registration.isEmpty()){action("Logo ansehen",()->preview(registration));action("Logo entfernen",()->{registration="";put("logoKey","");message("Logo wird beim Speichern entfernt.");});}
        title("Anordnung und Schrift");select("fontFamily","Schriftart",new String[]{"Arial","Helvetica","Times","Courier"});select("logoPosition","Logoposition",new String[]{"left","center","right"},new String[]{"Links","Mitte","Rechts"});select("contactPosition","Kontaktposition",new String[]{"left","right"},new String[]{"Links","Rechts"});select("companyAlign","Firmenname ausrichten",new String[]{"left","center","right"},new String[]{"Links","Mitte","Rechts"});
        String[][] numbers={{"logoWidth","Logobreite"},{"logoTop","Logo-Abstand oben"},{"logoX","Logo horizontal"},{"logoY","Logo vertikal"},{"companyNameSize","Schriftgröße Firmenname"},{"subtitleSize","Schriftgröße Untertitel"},{"contactSize","Schriftgröße Kontakt"},{"footerSize","Schriftgröße Fußzeile"},{"companyX","Firmenname horizontal"},{"companyY","Firmenname vertikal"},{"companyWidth","Breite Firmenname"},{"contactX","Kontakt horizontal"},{"contactY","Kontakt vertikal"},{"contactWidth","Kontaktbreite"},{"contactLineSpacing","Kontakt-Zeilenabstand"},{"contentX","Inhalt horizontal"},{"contentY","Inhalt vertikal"},{"contentWidth","Inhaltsbreite"},{"contentHeight","Inhaltshöhe"},{"contentSize","Schriftgröße Inhalt"}};
        note("Positionen, Größen und Abstände wie in der Webversion, in PDF-Punkten.");for(String[] f:numbers)input(f[0],f[1]).setInputType(12290);multiline("contentText","Vorschautext");
        title("Kopf- und Fußlinien");check("showHeaderLine","Kopflinie anzeigen");check("showFooterLine","Fußlinie anzeigen");for(String prefix:new String[]{"header","footer"}){String label=prefix.equals("header")?"Kopflinie":"Fußlinie";input(prefix+"LineColor",label+" Farbe (#RRGGBB)");select(prefix+"LineStyle",label+" Stil",new String[]{"solid","dashed","dotted"},new String[]{"Durchgezogen","Gestrichelt","Gepunktet"});for(String[] f:new String[][]{{"Thickness","Stärke"},{"X","Horizontal"},{"Y","Vertikal"},{"Width","Breite"}})input(prefix+"Line"+f[0],label+" "+f[1]).setInputType(12290);}input("headerLinePosition","Zusätzlicher Abstand Kopflinie").setInputType(12290);
        saveButton=action("Briefpapier speichern",this::save);action("PDF-Vorschau",()->{try{JSONObject draft=collect(true);validateLetterhead(draft);Intent i=new Intent(this,PdfActivity.class).putExtra("letterhead",draft.toString()).putExtra("logoRef",registration);startActivity(i);}catch(Exception e){message(e.getMessage());}});
    }
    @Override protected void onActivityResult(int request,int result,Intent data){if(request==403&&result==RESULT_OK&&data!=null&&data.getData()!=null){registration=data.getData().toString();try{getContentResolver().takePersistableUriPermission(data.getData(),Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}message("Logo ausgewählt; zum Übernehmen speichern.");return;}super.onActivityResult(request,result,data);}
    private void validateLetterhead(JSONObject value)throws Exception{for(String k:fields.keySet()){Object original=model.opt(k);if(original instanceof Number){String raw=value.optString(k).replace(',','.');double n=Double.parseDouble(raw);if(!Double.isFinite(n))throw new IllegalArgumentException("Bitte gültige Größen eingeben.");value.put(k,n);}}for(String k:new String[]{"headerLineColor","footerLineColor"})if(!value.optString(k).matches("#[0-9a-fA-F]{6}"))throw new IllegalArgumentException("Farben bitte als #RRGGBB eingeben.");if(registration.isEmpty())value.put("logoKey","");}
}
