package de.autopolish.nativeapp;

import android.content.*;
import android.graphics.*;
import android.graphics.pdf.*;
import android.net.Uri;
import android.os.*;
import android.print.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.util.UUID;

public class PdfActivity extends MediaFormActivity {
    private File file;
    private PdfRenderer renderer;
    private ParcelFileDescriptor descriptor;
    private final Object lock=new Object();
    private ImageView imageView;
    private TextView pageLabel;
    private Bitmap rendered;
    private int page,pageCount;
    private boolean rendering,closed;
    private LinearLayout toolsPanel;
    public static void open(Context c,String path,String title){c.startActivity(new Intent(c,PdfActivity.class).putExtra("path",path).putExtra("title",title));}
    @Override protected void onCreate(Bundle state){super.onCreate(state);shell(getIntent().getStringExtra("title")==null?"PDF-Vorschau":getIntent().getStringExtra("title"));pageLabel=Ui.text(this,"Dokument wird geladen …",16,Ui.BLACK,true);content.addView(pageLabel);imageView=new ImageView(this);imageView.setAdjustViewBounds(true);imageView.setBackgroundColor(Color.WHITE);content.addView(imageView,new LinearLayout.LayoutParams(-1,-2));
        toolsPanel=Ui.vertical(this,0);toolsPanel.setVisibility(android.view.View.GONE);content.addView(toolsPanel);LinearLayout original=content;content=toolsPanel;
        LinearLayout nav=new LinearLayout(this);Button prev=Ui.button(this,"‹",Ui.BLACK),next=Ui.button(this,"›",Ui.BLACK);prev.setContentDescription("Vorherige Seite");next.setContentDescription("Nächste Seite");LinearLayout.LayoutParams previousParams=new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48));previousParams.rightMargin=Ui.dp(this,8);nav.addView(prev,previousParams);nav.addView(next,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));nav.setGravity(android.view.Gravity.CENTER);nav.setPadding(0,Ui.dp(this,10),0,0);content.addView(nav);prev.setOnClickListener(v->{if(page>0&&!rendering){page--;renderPage();}});next.setOnClickListener(v->{if(page+1<pageCount&&!rendering){page++;renderPage();}});
        LinearLayout actions=new LinearLayout(this);content.addView(actions);Button printButton=action("Drucken",this::print);action("PDF speichern",()->{if(file==null){message("Dokument wird noch geladen.");return;}try{startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/pdf").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"Auto-Polish.pdf"),501);}catch(Exception e){message("Dateiauswahl konnte nicht geöffnet werden.");}});
        action("PDF teilen",()->{if(file==null)return;Uri uri=SharedFiles.uri(this,file);Intent i=new Intent(Intent.ACTION_SEND).setType("application/pdf").putExtra(Intent.EXTRA_STREAM,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);i.setClipData(ClipData.newRawUri("PDF",uri));try{startActivity(Intent.createChooser(i,"PDF teilen"));}catch(Exception e){message("Keine passende App installiert.");}});
        java.util.ArrayList<android.view.View> buttons=new java.util.ArrayList<>();for(int n=0;n<content.getChildCount();n++)if(content.getChildAt(n) instanceof Button)buttons.add(content.getChildAt(n));for(android.view.View v:buttons){content.removeView(v);Button b=(Button)v;b.setText(b.getText().toString().replace("PDF ",""));b.setTextSize(12);b.setPadding(0,0,0,0);b.setBackgroundColor(Color.TRANSPARENT);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,Ui.dp(this,48),1);actions.addView(b,ap);}
        content=original;
        requests.execute(()->{try{File target=new File(SharedFiles.directory(this),"Auto-Polish-"+UUID.randomUUID()+".pdf");if(getIntent().hasExtra("letterhead"))letterhead(target,new JSONObject(getIntent().getStringExtra("letterhead")));else if(getIntent().getStringExtra("path").startsWith("/api/tire-storages/")){String path=getIntent().getStringExtra("path");String id=path.substring("/api/tire-storages/".length(),path.length()-"/pdf".length());JSONObject record=ApiClient.request("GET","/api/tire-storages?id="+id,null).getJSONObject("record");try{byte[] bytes=ApiClient.download(path,40*1024*1024,12000);try(FileOutputStream out=new FileOutputStream(target)){out.write(bytes);}}catch(Exception serverError){TireDocument.write(target,record,key->image(key,1600));}}else{byte[] bytes=ApiClient.download(getIntent().getStringExtra("path"),40*1024*1024);try(FileOutputStream out=new FileOutputStream(target)){out.write(bytes);}}
            synchronized(lock){if(closed)return;descriptor=ParcelFileDescriptor.open(target,ParcelFileDescriptor.MODE_READ_ONLY);renderer=new PdfRenderer(descriptor);pageCount=renderer.getPageCount();file=target;}runOnUiThread(()->{toolsPanel.setVisibility(android.view.View.VISIBLE);renderPage();});
        }catch(Exception e){runOnUiThread(()->{if(!isDestroyed()){pageLabel.setText("PDF konnte nicht geladen werden: "+e.getMessage());action("Erneut versuchen",()->recreate());}});}});
    }
    private void renderPage(){if(renderer==null||rendering||closed)return;rendering=true;final int selected=page;requests.execute(()->{try{Bitmap bitmap; synchronized(lock){if(closed)return;try(PdfRenderer.Page current=renderer.openPage(selected)){float scale=1400f/Math.max(current.getWidth(),current.getHeight());bitmap=Bitmap.createBitmap(Math.max(1,Math.round(current.getWidth()*scale)),Math.max(1,Math.round(current.getHeight()*scale)),Bitmap.Config.ARGB_8888);bitmap.eraseColor(Color.WHITE);current.render(bitmap,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);}}runOnUiThread(()->{rendering=false;if(isDestroyed()){bitmap.recycle();return;}imageView.setImageBitmap(bitmap);if(rendered!=null)rendered.recycle();rendered=bitmap;pageLabel.setText("Seite "+(selected+1)+" von "+pageCount);});}catch(Exception e){runOnUiThread(()->{rendering=false;if(!isDestroyed())pageLabel.setText("Seite konnte nicht angezeigt werden.");});}});}
    private void print(){if(file==null){message("Dokument wird noch geladen.");return;}final File ready=file;final int count=pageCount;((PrintManager)getSystemService(PRINT_SERVICE)).print("Auto-Polish",new PrintDocumentAdapter(){public void onLayout(PrintAttributes old,PrintAttributes next,CancellationSignal cancel,LayoutResultCallback callback,Bundle extra){if(cancel.isCanceled()){callback.onLayoutCancelled();return;}callback.onLayoutFinished(new PrintDocumentInfo.Builder("Auto-Polish.pdf").setContentType(PrintDocumentInfo.CONTENT_TYPE_DOCUMENT).setPageCount(count).build(),true);}public void onWrite(PageRange[] pages,ParcelFileDescriptor target,CancellationSignal cancel,WriteResultCallback callback){try(InputStream in=new FileInputStream(ready);OutputStream out=new FileOutputStream(target.getFileDescriptor())){byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1){if(cancel.isCanceled()){callback.onWriteCancelled();return;}out.write(buffer,0,n);}callback.onWriteFinished(new PageRange[]{PageRange.ALL_PAGES});}catch(Exception e){callback.onWriteFailed(e.getMessage());}}},new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).build());}
    @Override protected void onActivityResult(int request,int result,Intent data){if(request==501&&result==RESULT_OK&&data!=null&&data.getData()!=null){Uri destination=data.getData();requests.execute(()->{try(InputStream in=new FileInputStream(file);OutputStream out=getContentResolver().openOutputStream(destination)){if(out==null)throw new IOException("Datei konnte nicht geöffnet werden.");byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);runOnUiThread(()->message("PDF gespeichert."));}catch(Exception e){runOnUiThread(()->message("PDF konnte nicht gespeichert werden."));}});return;}super.onActivityResult(request,result,data);}
    private float number(JSONObject c,String key,float fallback){return (float)c.optDouble(key,fallback);}
    private void text(Canvas canvas,Paint paint,String value,float x,float y,float size,float width){paint.setStyle(Paint.Style.FILL);paint.setPathEffect(null);paint.setTextSize(size);for(String paragraph:value.split("\n",-1)){String line="";for(String word:paragraph.split(" ")){String candidate=line.isEmpty()?word:line+" "+word;if(paint.measureText(candidate)>width&&!line.isEmpty()){canvas.drawText(line,x,y,paint);y+=size*1.35f;line=word;}else line=candidate;}canvas.drawText(line,x,y,paint);y+=size*1.35f;}}
    private void letterhead(File target,JSONObject c)throws Exception{PdfDocument document=new PdfDocument();try{PdfDocument.Page p=document.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas canvas=p.getCanvas();canvas.drawColor(Color.WHITE);Paint paint=new Paint(3);paint.setColor(Color.BLACK);String family=c.optString("fontFamily","Arial");paint.setTypeface(Typeface.create(family.equals("Times")?"serif":family.equals("Courier")?"monospace":"sans-serif",Typeface.NORMAL));String logo=getIntent().getStringExtra("logoRef");if(logo!=null&&!logo.isEmpty()){Bitmap b=image(logo,1200);float w=number(c,"logoWidth",250),h=b.getHeight()*w/b.getWidth();canvas.drawBitmap(b,null,new RectF(number(c,"logoX",45),number(c,"logoY",8),number(c,"logoX",45)+w,number(c,"logoY",8)+h),paint);b.recycle();}
            text(canvas,paint,c.optString("companyName"),number(c,"companyX",45),number(c,"companyY",92),number(c,"companyNameSize",22),number(c,"companyWidth",280));text(canvas,paint,c.optString("subtitle"),number(c,"companyX",45),number(c,"companyY",92)+18,number(c,"subtitleSize",10),number(c,"companyWidth",280));
            text(canvas,paint,c.optString("street")+"\n"+c.optString("postalCity")+"\n"+c.optString("phone")+"\n"+c.optString("email")+"\n"+c.optString("website"),number(c,"contactX",365),number(c,"contactY",32),number(c,"contactSize",8.5f),number(c,"contactWidth",185));text(canvas,paint,c.optString("contentText"),number(c,"contentX",45),number(c,"contentY",235),number(c,"contentSize",10),number(c,"contentWidth",505));text(canvas,paint,c.optString("bank")+"\nSteuernummer: "+c.optString("taxNumber")+" · Inhaber: "+c.optString("owner"),45,803,number(c,"footerSize",6.5f),505);
            for(String prefix:new String[]{"header","footer"})if(c.optBoolean(prefix.equals("header")?"showHeaderLine":"showFooterLine",true)){paint.setColor(Color.parseColor(c.optString(prefix+"LineColor","#000000")));paint.setStrokeWidth(number(c,prefix+"LineThickness",1));String style=c.optString(prefix+"LineStyle");paint.setPathEffect(style.equals("solid")?null:new DashPathEffect(style.equals("dotted")?new float[]{1,3}:new float[]{5,4},0));float x=number(c,prefix+"LineX",45),y=number(c,prefix+"LineY",prefix.equals("header")?92:58);if(prefix.equals("footer"))y=842-y;canvas.drawLine(x,y,x+number(c,prefix+"LineWidth",505),y,paint);}document.finishPage(p);try(OutputStream out=new FileOutputStream(target)){document.writeTo(out);}} finally {document.close();}
    }
    @Override protected void onDestroy(){synchronized(lock){closed=true;if(renderer!=null)renderer.close();if(descriptor!=null)try{descriptor.close();}catch(Exception ignored){}}if(rendered!=null){imageView.setImageDrawable(null);rendered.recycle();}super.onDestroy();}
}

